import puppeteer, { type Page } from 'puppeteer';
import { appConfig } from '../src/config';
import {
    challengeWordsFingerprint,
    validateChallengeWords,
} from '../src/domain/challenges/challengeWords';
import {
    CHALLENGE_REQUEST_ROUTE,
    CHALLENGE_TOPIC,
    responseSaidFromChallengeOperation,
} from '../src/services/challenges.service';
import {
    connectSignifyClient,
    waitOperation,
} from '../src/signify/client';
import {
    chromeArgs,
    connectBrowserAgent,
    dispatchClick,
    dispatchEnabledClick,
    logStage,
    setInputValue,
    sleep,
    startViteIfNeeded,
    waitForElementPresent,
    waitForText,
} from './support/browserHarness';
import {
    openContactDetail,
    resolveOobiInContacts,
} from './support/contactUiHarness';
import {
    addAgentEndRole,
    createRole,
    createWitnessedIdentifier,
    resolveOobi,
    uniqueAlias,
    waitForEvent,
    waitForKeriaOperation,
    type Role,
} from './support/keria';

/** Browser app URL; a local Vite server is started when unreachable. */
const appUrl =
    process.env.CONTACT_CHALLENGE_SMOKE_URL ?? 'http://127.0.0.1:5177';

/** Build a Node Signify role for the same controller as the browser wallet. */
const roleFromPasscode = async (
    passcode: string,
    name: string
): Promise<Role> => {
    const connected = await connectSignifyClient({
        adminUrl: appConfig.keria.adminUrl,
        bootUrl: appConfig.keria.bootUrl,
        passcode,
        tier: appConfig.defaultTier,
    });

    let role: Role;
    role = {
        name,
        passcode,
        client: connected.client,
        controllerPre: connected.state.controllerPre,
        agentPre: connected.state.agentPre,
        waitEvent: async (result, label) => waitForEvent(role, result, label),
        waitOperation: async (operation, label) =>
            waitForKeriaOperation(role, operation, label),
    };

    return role;
};

/** Read challenge words generated by the browser contact detail workflow. */
const generatedChallengeWords = async (page: Page): Promise<string[]> => {
    await page.waitForSelector('[data-testid="challenge-generated-words"]', {
        timeout: 30_000,
    });
    const text = await page.$eval(
        '[data-testid="challenge-generated-words"]',
        (element) => element.textContent ?? ''
    );
    const words = text.trim().split(/\s+/u).filter(Boolean);
    if (words.length !== 12 && words.length !== 24) {
        throw new Error(
            `Expected challenge words, got ${words.length} tokens.`
        );
    }

    return words;
};

/** Generate valid challenge words directly through the harness KERIA role. */
const generatedKeriaChallengeWords = async (role: Role): Promise<string[]> => {
    const challenge = await role.client.challenges().generate(128);
    const words = Array.isArray(challenge.words) ? challenge.words : [];
    const error = validateChallengeWords(words);
    if (error !== null) {
        throw new Error(error);
    }

    return words.map((word) => word.trim().toLowerCase());
};

/** Send a challenge request EXN without embedding the challenge words. */
const sendChallengeRequest = async ({
    challenger,
    challengerAlias,
    recipientAid,
    words,
}: {
    challenger: Role;
    challengerAlias: string;
    recipientAid: string;
    words: readonly string[];
}): Promise<string> => {
    const challengeId = `smoke-challenge-${Date.now()}-${Math.random()
        .toString(16)
        .slice(2)}`;
    const hab = await challenger.client.identifiers().get(challengerAlias);
    await challenger.client.exchanges().send(
        challengerAlias,
        CHALLENGE_TOPIC,
        hab,
        CHALLENGE_REQUEST_ROUTE,
        {
            challengeId,
            wordsHash: challengeWordsFingerprint(words),
            strength: words.length === 24 ? 256 : 128,
        },
        {},
        [recipientAid]
    );

    return challengeId;
};

const isRecord = (value: unknown): value is Record<string, unknown> =>
    typeof value === 'object' && value !== null;

const exchangeChallengeId = (value: unknown): string | null => {
    if (!isRecord(value) || !isRecord(value.exn) || !isRecord(value.exn.a)) {
        return null;
    }

    const challengeId = value.exn.a.challengeId;
    return typeof challengeId === 'string' ? challengeId : null;
};

const exchangeSaid = (value: unknown): string | null => {
    if (!isRecord(value) || !isRecord(value.exn)) {
        return null;
    }

    const said = value.exn.d;
    return typeof said === 'string' ? said : null;
};

/** Query challenge request EXNs because synthetic notifications derive from them. */
const challengeRequestExchanges = async (role: Role): Promise<unknown[]> => {
    const response = await role.client.fetch('/exchanges/query', 'POST', {
        filter: {
            '-r': CHALLENGE_REQUEST_ROUTE,
        },
        limit: 50,
    });
    const raw: unknown = await response.json();
    return Array.isArray(raw) ? raw : [];
};

/** Wait until the recipient KERIA agent has indexed a challenge request EXN. */
const waitForChallengeRequestExchange = async (
    role: Role,
    challengeId: string
): Promise<string> => {
    for (let attempt = 0; attempt < 45; attempt += 1) {
        const exchanges = await challengeRequestExchanges(role);
        const exchange = exchanges.find(
            (candidate) => exchangeChallengeId(candidate) === challengeId
        );
        if (exchange !== undefined) {
            const said = exchangeSaid(exchange);
            if (said !== null) {
                return said;
            }
        }
        await sleep(1000);
    }

    throw new Error(`Challenge request ${challengeId} was not indexed.`);
};

/** Complete challenger-side verify/wait/responded acceptance. */
const verifyChallengeResponse = async ({
    challenger,
    responderAid,
    words,
    label,
}: {
    challenger: Role;
    responderAid: string;
    words: readonly string[];
    label: string;
}): Promise<void> => {
    const operation = await challenger.client
        .challenges()
        .verify(responderAid, [...words]);
    const completed = await waitOperation(challenger.client, operation, {
        label: `${challenger.name}: ${label}`,
        ...appConfig.operations,
        timeoutMs: 120_000,
    });
    const responseSaid = responseSaidFromChallengeOperation(completed);
    const response = await challenger.client
        .challenges()
        .responded(responderAid, responseSaid);
    if (!response.ok) {
        throw new Error(
            `KERIA rejected ${label}: ${response.status} ${response.statusText}`
        );
    }
};

/** Open the notification quick panel from any route state. */
const openNotificationsBell = async (page: Page): Promise<void> => {
    await page.keyboard.press('Escape');
    await dispatchClick(page, '[data-testid="notifications-open"]');
};

interface ChallengeNotificationCardSnapshot {
    challengeId: string | null;
    text: string;
}

/** Return visible challenge notification cards with hidden challenge ids. */
const challengeNotificationCards = (
    page: Page
): Promise<ChallengeNotificationCardSnapshot[]> =>
    page.evaluate(() =>
        Array.from(
            globalThis.document.querySelectorAll(
                '[data-testid="challenge-notification-card"]'
            )
        ).map((card) => {
            const input = card.querySelector('input[name="challengeId"]');
            return {
                challengeId:
                    input instanceof globalThis.HTMLInputElement
                        ? input.value
                        : null,
                text: card.textContent ?? '',
            };
        })
    );

/** Wait for the matching synthetic challenge notification card. */
const waitForChallengeNotificationCard = async (
    page: Page,
    challengeId: string
): Promise<void> => {
    await openNotificationsBell(page);

    const timeoutAt = Date.now() + 45_000;
    let cards: ChallengeNotificationCardSnapshot[] = [];
    while (Date.now() < timeoutAt) {
        cards = await challengeNotificationCards(page);
        if (cards.some((card) => card.challengeId === challengeId)) {
            logStage('challenge.notification.card.ready', { challengeId });
            return;
        }
        await sleep(250);
    }

    const visibleText = await page.evaluate(
        () => globalThis.document.body.textContent?.slice(0, 4000) ?? ''
    );
    throw new Error(
        `Challenge notification card ${challengeId} did not appear. Cards: ${JSON.stringify(cards)} Visible text: ${visibleText}`
    );
};

/** Selector that avoids MUI's hidden autosize mirror textarea. */
const visibleChallengeResponseTextarea = (scope: string): string =>
    `${scope} [data-testid="challenge-notification-response-input"] textarea:not([aria-hidden="true"])`;

/** Set words in the matching top-bar challenge notification card. */
const setCardChallengeResponseWords = async (
    page: Page,
    challengeId: string,
    words: readonly string[]
): Promise<void> => {
    await page.evaluate(
        ({ targetChallengeId, nextValue }) => {
            const card = Array.from(
                globalThis.document.querySelectorAll(
                    '[data-testid="challenge-notification-card"]'
                )
            ).find((candidate) => {
                const input = candidate.querySelector(
                    'input[name="challengeId"]'
                );
                return (
                    input instanceof globalThis.HTMLInputElement &&
                    input.value === targetChallengeId
                );
            });
            if (!(card instanceof globalThis.HTMLElement)) {
                throw new Error(
                    `Challenge card ${targetChallengeId} was not found.`
                );
            }
            const textarea = card.querySelector(
                '[data-testid="challenge-notification-response-input"] textarea:not([aria-hidden="true"])'
            );
            if (!(textarea instanceof globalThis.HTMLTextAreaElement)) {
                throw new Error(
                    `Challenge card ${targetChallengeId} response textarea was not found.`
                );
            }
            const valueSetter = Object.getOwnPropertyDescriptor(
                globalThis.HTMLTextAreaElement.prototype,
                'value'
            )?.set;
            if (valueSetter === undefined) {
                throw new Error('Unable to set challenge response words.');
            }
            textarea.focus();
            valueSetter.call(textarea, nextValue);
            textarea.dispatchEvent(
                new globalThis.Event('input', { bubbles: true })
            );
            textarea.dispatchEvent(
                new globalThis.Event('change', { bubbles: true })
            );
        },
        { targetChallengeId: challengeId, nextValue: words.join(' ') }
    );
};

/** Click the matching top-bar challenge response submit button. */
const clickCardChallengeResponseSubmit = async (
    page: Page,
    challengeId: string
): Promise<void> => {
    const timeoutAt = Date.now() + 30_000;
    let lastState = 'not checked';

    while (Date.now() < timeoutAt) {
        lastState = await page.evaluate((targetChallengeId) => {
            const card = Array.from(
                globalThis.document.querySelectorAll(
                    '[data-testid="challenge-notification-card"]'
                )
            ).find((candidate) => {
                const input = candidate.querySelector(
                    'input[name="challengeId"]'
                );
                return (
                    input instanceof globalThis.HTMLInputElement &&
                    input.value === targetChallengeId
                );
            });
            if (!(card instanceof globalThis.HTMLElement)) {
                return 'missing-card';
            }
            const button = card.querySelector(
                '[data-testid="challenge-notification-response-submit"]'
            );
            if (!(button instanceof globalThis.HTMLButtonElement)) {
                return 'missing-button';
            }
            if (button.disabled) {
                return 'disabled';
            }
            button.click();
            return 'clicked';
        }, challengeId);
        if (lastState === 'clicked') {
            return;
        }
        await sleep(250);
    }

    throw new Error(
        `Challenge card ${challengeId} submit did not become enabled: ${lastState}`
    );
};

/** Respond to a challenge request from the top-bar notification card. */
const respondFromBellNotification = async (
    page: Page,
    words: readonly string[],
    challengeId: string
): Promise<void> => {
    logStage('challenge.bell.response.start', { challengeId });
    await waitForChallengeNotificationCard(page, challengeId);
    await setCardChallengeResponseWords(page, challengeId, words);
    await clickCardChallengeResponseSubmit(page, challengeId);
    logStage('challenge.bell.response.submitted', { challengeId });
};

/** Respond to a challenge request from the notification detail route. */
const respondFromNotificationDetail = async (
    page: Page,
    words: readonly string[],
    challengeId: string
): Promise<void> => {
    logStage('challenge.detail.response.start', { challengeId });
    await waitForChallengeNotificationCard(page, challengeId);
    await page.evaluate((targetChallengeId) => {
        const card = Array.from(
            globalThis.document.querySelectorAll(
                '[data-testid="challenge-notification-card"]'
            )
        ).find((candidate) => {
            const input = candidate.querySelector('input[name="challengeId"]');
            return (
                input instanceof globalThis.HTMLInputElement &&
                input.value === targetChallengeId
            );
        });
        const link = card?.querySelector(
            '[data-testid="challenge-notification-detail-link"]'
        );
        if (!(link instanceof globalThis.HTMLElement)) {
            throw new Error(
                `Challenge detail link for ${targetChallengeId} was not found.`
            );
        }
        link.click();
    }, challengeId);
    const timeoutAt = Date.now() + 10_000;
    while (Date.now() < timeoutAt) {
        const onDetail = await page.evaluate(() =>
            globalThis.location.pathname.startsWith('/notifications/')
        );
        if (onDetail) {
            break;
        }
        await sleep(250);
    }
    if (
        !(await page.evaluate(() =>
            globalThis.location.pathname.startsWith('/notifications/')
        ))
    ) {
        throw new Error(`Notification detail route did not open: ${page.url()}`);
    }
    await waitForElementPresent(
        page,
        visibleChallengeResponseTextarea('main'),
        'Challenge notification detail textarea'
    );
    await setInputValue(
        page,
        visibleChallengeResponseTextarea('main'),
        words.join(' ')
    );
    await dispatchEnabledClick(
        page,
        'main [data-testid="challenge-notification-response-submit"]',
        'challenge detail response submit'
    );
    logStage('challenge.detail.response.submitted');
};

const vite = await startViteIfNeeded(appUrl);
const browser = await puppeteer.launch({
    headless: 'new',
    args: chromeArgs,
    protocolTimeout: 300_000,
});

try {
    const page = await browser.newPage();
    page.setDefaultTimeout(60_000);
    page.setDefaultNavigationTimeout(60_000);
    page.on('pageerror', (error) => {
        console.error(`[browser:pageerror] ${error.message}`);
    });
    page.on('console', (message) => {
        if (message.type() === 'error' || message.type() === 'warning') {
            console.error(`[browser:${message.type()}] ${message.text()}`);
        }
    });
    const browserPasscode = await connectBrowserAgent(page, { appUrl });
    const browserRole = await roleFromPasscode(
        browserPasscode,
        'ui-challenge-browser'
    );
    const browserAlias = uniqueAlias('ui-challenge-browser');
    logStage('browser.identifier.create.start', { browserAlias });
    const browserAid = await createWitnessedIdentifier(
        browserRole,
        browserAlias
    );
    const browserOobi = await addAgentEndRole(browserRole, browserAlias);
    logStage('browser.identifier.ready', {
        browserAlias,
        browserAid: browserAid.prefix,
    });

    const harness = await createRole('ui-challenge-harness');
    const harnessAlias = uniqueAlias('ui-challenge-harness');
    logStage('harness.identifier.create.start', { harnessAlias });
    await createWitnessedIdentifier(harness, harnessAlias);
    const harnessOobi = await addAgentEndRole(harness, harnessAlias);
    logStage('harness.identifier.ready', { harnessAlias });
    logStage('harness.resolve.browser.start', { browserAlias });
    await resolveOobi(harness, browserOobi, browserAlias);
    logStage('harness.resolve.browser.ready', { browserAlias });

    await resolveOobiInContacts(page, {
        alias: harnessAlias,
        oobi: harnessOobi,
        requireResolved: true,
    });
    await openContactDetail(page, harnessAlias);
    await waitForText(page, '[data-testid="contact-detail"]', 'Unverified');

    await dispatchEnabledClick(
        page,
        '[data-testid="challenge-generate-submit"]',
        'challenge generate submit'
    );
    const words = await generatedChallengeWords(page);
    logStage('challenge.detail.generate.ready', { wordCount: words.length });

    logStage('harness.respond.browserChallenge.start');
    await harness.client
        .challenges()
        .respond(harnessAlias, browserAid.prefix, words);
    logStage('harness.respond.browserChallenge.submitted');
    await waitForText(
        page,
        '[data-testid="contact-detail"]',
        'Verified',
        180_000
    );
    logStage('challenge.detail.verified');
    await page.waitForFunction(
        () =>
            globalThis.document.querySelector(
                '[data-testid="challenge-generated-words"]'
            ) === null,
        { timeout: 30_000 }
    );

    const detailWords = await generatedKeriaChallengeWords(harness);
    logStage('harness.challenge.detail.send.start', {
        wordCount: detailWords.length,
    });
    const detailChallengeId = await sendChallengeRequest({
        challenger: harness,
        challengerAlias: harnessAlias,
        recipientAid: browserAid.prefix,
        words: detailWords,
    });
    logStage('harness.challenge.detail.send.ready', { detailChallengeId });
    await waitForChallengeRequestExchange(browserRole, detailChallengeId);
    logStage('browser.challenge.detail.indexed', { detailChallengeId });
    await respondFromNotificationDetail(page, detailWords, detailChallengeId);
    await verifyChallengeResponse({
        challenger: harness,
        responderAid: browserAid.prefix,
        words: detailWords,
        label: 'verifying detail challenge response',
    });
    logStage('harness.challenge.detail.verified', { detailChallengeId });

    const bellWords = await generatedKeriaChallengeWords(harness);
    logStage('harness.challenge.bell.send.start', {
        wordCount: bellWords.length,
    });
    const bellChallengeId = await sendChallengeRequest({
        challenger: harness,
        challengerAlias: harnessAlias,
        recipientAid: browserAid.prefix,
        words: bellWords,
    });
    logStage('harness.challenge.bell.send.ready', { bellChallengeId });
    await waitForChallengeRequestExchange(browserRole, bellChallengeId);
    logStage('browser.challenge.bell.indexed', { bellChallengeId });
    await respondFromBellNotification(page, bellWords, bellChallengeId);
    await verifyChallengeResponse({
        challenger: harness,
        responderAid: browserAid.prefix,
        words: bellWords,
        label: 'verifying bell challenge response',
    });
    logStage('harness.challenge.bell.verified', { bellChallengeId });

    console.log(
        JSON.stringify(
            {
                status: 'passed',
                browserAlias,
                harnessAlias,
                wordCount: words.length,
                bellWordCount: bellWords.length,
                detailWordCount: detailWords.length,
            },
            null,
            2
        )
    );
} finally {
    await browser.close();
    if (vite !== null) {
        vite.kill('SIGTERM');
    }
}
